######################## default configuration ####################
baseURL = "https://incubyteco.github.io/"
title = "Incubyte Blog"
theme = "bigspring"
# post pagination
paginate = "12"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-178057567-1"
# unsafe html
[markup.goldmark.renderer]
unsafe = true

[params.variables]
primary_color = "#5cc5d5"
text_color = "#777"
text_color_dark = "#222"
body_color = "#fff"
border_color = "#ECECEC"
black = "#000"
white = "#fff"
light = "#e6e6e9"
