# main menu

[[main]]
name = "Articles"
url = "/"
weight = 1


[[main]]
name = "About"
weight = 2

[[main]]
name = "Why Incubyte"
url = "https://incubyte.co/why-incubyte"
parent = "About"
weight = 1

[[main]]
name = "Events"
url = "https://www.incubyte.co/events"
parent = "About"
weight = 2

[[main]]
name = "Inspiration!"
url = "https://incubyte.co/inspiration"
weight = 3
parent = "About"

[[main]]
name = "Work"
weight = 3

[[main]]
name = "Software Development"
url = "https://incubyte.co/design-and-develop"
parent = "Work"
weight = 1

[[main]]
name = "Software Modernization"
url = "https://www.incubyte.co/enhance-and-modernize"
parent = "Work"
weight = 2

[[main]]
name = "Software Quality Assessment"
url = "https://www.incubyte.co/enhance-and-modernize"
parent = "Work"
weight = 3


[[main]]
name = "Careers"
url = "https://incubyte.co/careers"
weight = 4


# footer menu left
[[footer_left]]
name = "Why Incubyte"
url = "https://incubyte.co/why-incubyte"
weight = 1

[[footer_left]]
name = "Events"
url = "https://www.incubyte.co/events"
weight = 2

[[footer_left]]
name = "Inspiration!"
url = "https://incubyte.co/inspiration"
weight = 3

[[footer_left]]
name = "Careers"
url = "https://www.incubyte.co/careers"
weight = 4


# footer menu middle
[[footer_middle]]
name = "Software Development"
url = "https://www.incubyte.co/design-and-deveop"
weight = 1

[[footer_middle]]
name = "Software Modernization"
url = "https://www.incubyte.co/enhance-and-modernize"
weight = 2

[[footer_middle]]
name = "Software Quality Assessment"
url = "https://www.incubyte.co/enhance-and-modernize"
weight = 3


# footer menu right
[[footer_right]]
name = "Let's Get Started"
url = "https://incubyte.co/#Get-in-touch"
weight = 1

[[footer_right]]
name = "Work With Us"
url = "https://incubyte.co/careers"
weight = 2
