# main menu

[[main]]
name = "About"
weight = 1

[[main]]
name = "Why Incubyte"
url = "https://incubyte.co/why-incubyte"
parent = "About"
weight = 1

[[main]]
name = "Events"
url = "https://www.incubyte.co/events"
parent = "About"
weight = 2


[[main]]
name = "Work"
weight = 2

[[main]]
name = "Product Development"
url = "https://www.incubyte.co/software-development"
parent = "Work"
weight = 1

[[main]]
name = "Software Modernization"
url = "https://www.incubyte.co/enhance-and-modernize"
parent = "Work"
weight = 2

[[main]]
name = "Consulting"
url = "https://www.incubyte.co/consulting"
parent = "Work"
weight = 3

[[main]]
name = "Virtual CTO"
url = "https://www.incubyte.co/virtual-cto"
parent = "Work"
weight = 4

[[main]]
name = "Resources"
weight = 3

[[main]]
name = "Inspiration!"
url = "https://incubyte.co/inspiration"
weight = 1
parent = "Resources"

[[main]]
name = "Blog"
url = "/"
parent = "Resources"
weight = 2

[[main]]
name = "Careers"
url = "https://incubyte.co/careers"
weight = 4


# footer menu left
[[footer_left]]
name = "Why Incubyte"
url = "https://incubyte.co/why-incubyte"
weight = 1

[[footer_left]]
name = "Events"
url = "https://www.incubyte.co/events"
weight = 2

[[footer_left]]
name = "Inspiration!"
url = "https://incubyte.co/inspiration"
weight = 3


# footer menu middle
[[footer_middle]]
name = "Product Development"
url = "https://www.incubyte.co/software-development"
weight = 1

[[footer_middle]]
name = "Software Modernization"
url = "https://www.incubyte.co/enhance-and-modernize"
weight = 2

[[footer_middle]]
name = "Consulting"
url = "https://www.incubyte.co/consulting"
weight = 3

[[footer_middle]]
name = "Virtual CTO"
url = "https://www.incubyte.co/virtual-cto"
weight = 4

# footer menu right
[[footer_right]]
name = "Let's Get Started"
url = "https://www.incubyte.co/lets-get-started"
weight = 1

[[footer_right]]
name = "Work With Us"
url = "https://incubyte.co/careers"
weight = 2
