# main menu

[[main]]
name = "About"
weight = 1

[[main]]
name = "Why Incubyte"
url = "https://incubyte.co/why-incubyte"
parent = "About"
weight = 1

[[main]]
name = "Events"
url = "https://www.incubyte.co/events"
parent = "About"
weight = 2


[[main]]
name = "Work"
weight = 2

[[main]]
name = "Product Development"
url = "https://www.incubyte.co/software-development"
parent = "Work"
weight = 1

[[main]]
name = "Software Modernization"
url = "https://www.incubyte.co/enhance-and-modernize"
parent = "Work"
weight = 2

[[main]]
name = "Consulting"
url = "https://www.incubyte.co/consulting"
parent = "Work"
weight = 3

[[main]]
name = "Virtual CTO"
url = "https://www.incubyte.co/virtual-cto"
parent = "Work"
weight = 4

[[main]]
name = "Resources"
weight = 3

[[main]]
name = "Inspiration!"
url = "https://incubyte.co/inspiration"
weight = 1
parent = "Resources"

[[main]]
name = "Blog"
url = "/"
parent = "Resources"
weight = 2

[[main]]
name = "Careers"
url = "https://incubyte.co/careers"
weight = 4


# footer menu left
[[footer_left]]
name = "home"
url = "https://incubyte.co/"
weight = 1

[[footer_left]]
name = "highlights"
url = "https://www.incubyte.co/highlights"
weight = 2

[[footer_left]]
name = "solutions"
url = "https://www.incubyte.co/solutions"
weight = 3

[[footer_left]]
name = "about us"
url = "https://www.incubyte.co/why-incubyte"
weight = 4

[[footer_left]]
name = "our team"
url = "https://www.incubyte.co/our-team"
weight = 5


# footer menu middle
[[footer_middle]]
name = "careers"
url = "https://www.incubyte.co/careers"
weight = 1

[[footer_middle]]
name = "inspiration"
url = "https://www.incubyte.co/inspiration"
weight = 2

[[footer_middle]]
name = "blog"
url = "https://blog.incubyte.co/"
weight = 3

[[footer_middle]]
name = "community"
url = "https://www.incubyte.co/events"
weight = 4

[[footer_middle]]
name = "ai playground"
url = "https://www.incubyte.co/ai-playground"
weight = 5

[[footer_middle]]
name = "contact"
url = "https://www.incubyte.co/lets-get-started"
weight = 6

# footer menu right
[[footer_right]]
name = "Let's Get Started"
url = "https://www.incubyte.co/lets-get-started"
weight = 1

[[footer_right]]
name = "Work With Us"
url = "https://incubyte.co/careers"
weight = 2
