# main menu
[[main]]
name = "Home"
url = "https://incubyte.co/"
weight = 1

[[main]]
name = "Articles"
url = "/"
weight = 2


[[main]]
name = "About"
weight = 3

[[main]]
name = "Why Incubyte"
url = "https://incubyte.co/why-incubyte"
parent = "About"
weight = 1

[[main]]
name = "Events"
url = "https://www.incubyte.co/events"
parent = "About"
weight = 2

[[main]]
name = "Inspiration!"
url = "https://incubyte.co/inspiration"
weight = 3
parent = "About"

[[main]]
name = "Work"
weight = 4

[[main]]
name = "Software Development"
url = "https://incubyte.co/design-and-develop"
parent = "Work"
weight = 1

[[main]]
name = "Software Modernization"
url = "https://www.incubyte.co/enhance-and-modernize"
parent = "Work"
weight = 2

[[main]]
name = "Software Quality Assessment"
url = "https://www.incubyte.co/enhance-and-modernize"
parent = "Work"
weight = 3


[[main]]
name = "Careers"
url = "https://incubyte.co/careers"
weight = 5


# footer menu left
[[footer_left]]
name = "Careers"
url = "https://www.incubyte.co/careers"

[[footer_left]]
name = "Why Incubyte"
url = "https://incubyte.co/why-incubyte"


# footer menu middle
[[footer_middle]]
name = "Design And Develop"
url = "https://www.incubyte.co/design-and-deveop"

[[footer_middle]]
name = "Enhance and Modernize"
url = "https://www.incubyte.co/enhance-and-modernize"


# footer menu right
[[footer_right]]
name = "Get In Touch"
url = "https://www.incubyte.co/events"
